apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- ../../base/examiner/
configMapGenerator:
- name: examiner-env
  literals:
  - "ECHO_VALUE=\"\U0001F3A2 CloudLand 2023 R0ckX \U0001F3B8\""
replicas:
- name: app
  count: 2
images:
- name: app
  newName: "quay.io/heubeck/examiner" # {"$imagepolicy": "apps:examiner-app:name"}
  newTag: 1.11.5 # {"$imagepolicy": "apps:examiner-app:tag"}
patches:
- patch: |-
    - op: replace
      path: /spec/policy/semver/range
      value: "~1.11"
  target:
    group: image.toolkit.fluxcd.io
    kind: ImagePolicy
    version: v1beta1
- patch: |-
    - op: replace
      path: /spec/imageRepositoryRef/name
      value: "examiner-app"
  target:
    group: image.toolkit.fluxcd.io
    kind: ImagePolicy
    version: v1beta1
