---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/podinfo/
configMapGenerator:
- name: podinfo-env
  literals:
  - ECHO_VALUE="🎢 CloudLand 2023 R0ckX 🎸"
replicas:
  - name: app
    count: 1
images:
  - name: app
    newName: "ghcr.io/stefanprodan/podinfo:6.3.6" # {"$imagepolicy": "apps:podinfo"}
