---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- ../../base/podinfo/
configMapGenerator:
- name: podinfo-env
  literals:
  - PODINFO_UI_MESSAGE="🎢 CloudLand 2023 R0ckX hard 🎸"
  - PODINFO_BACKEND_URL="http://podinfo-app.apps/echo"
replicas:
  - name: app
    count: 1
images:
  - name: app
    newName: "ghcr.io/stefanprodan/podinfo:6.3.6" # {"$imagepolicy": "apps:podinfo-app"}
