apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: examiner
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
