---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: examiner-
labels:
- pairs:
    app.kubernetes.io/name: examiner
  includeSelectors: true
resources:
- ../app
- flux-image-policy.yaml
patchesStrategicMerge:
- k8s-deployment.yaml
- k8s-ingress.yaml
- flux-image-repository.yaml
- k8s-network-policies.yaml
