---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: podinfo-env
          livenessProbe:
            exec:
             command:
             - podcli
             - check
             - http
             - localhost:9898/healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:9898/readyz
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
