---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: podinfo-
labels:
- pairs:
    app.kubernetes.io/name: podinfo
  includeSelectors: true
resources:
- ../app
patches:
- path: k8s-deployment.yaml
- path: k8s-service.yaml
- path: k8s-ingress.yaml
- path: flux-image-repository.yaml
- path: k8s-network-policies.yaml
