---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../app
patchesStrategicMerge:
- k8s-deployment.yaml
- k8s-service.yaml
- k8s-ingress.yaml
- flux-image-policy.yaml
- flux-image-repository.yaml
